### PR TITLE
Add Google Colab badge and links to README

### PR DESCRIPTION
**Pull request by matt-graham**
Adds links to run tutorial notebook on Google Colab as an alternative to setting up dependencies locally README file.

### CODE REVIEW

**Comment by pierreglaser** [comment]
Thanks, that's helpful. Running the notebook on `colab`, it seems like `flax` is not installed by default on `colab`. Is there any other way to ensure that `flax` is installed when running the notebook (as url parameters?) than having a cell with `!pip install flax` in the notebook?

**Comment by matt-graham** [comment]
Good point, I forgot about the additional dependencies. Unfortunately I don't know that there is a way to install dependencies other than calling `pip` directly in a notebook cell; to avoid the `pip` command getting run when running locally you can test for the presence of the `google.colab` module (which generally will only be available when running on Colab) and only run if this is present

```Python
try:
    import google.colab
    # Running on Google Colab therefore install additional dependencies
    !pip install flax numpyro
except ImportError:
    # Assume dependencies installed if not running on Colab
    pass
```

**Comment by pierreglaser** [comment]
Just tried your proposed solution on colab, seems like its working. Let's add this cell to the notebook and merge then.

**Comment by pierreglaser** [comment]
Thanks @matt-graham! Merging.

**Pull request merged**
